package main

import (
	"fmt"
	"time"

	"github.com/kelvins/sunrisesunset"
)

func printOneLine(latitude float64, longitude float64, utcOffset float64, date time.Time) {
	p := sunrisesunset.Parameters{
		Latitude:  latitude,
		Longitude: longitude,
		UtcOffset: utcOffset,
		Date:      date,
	}

	startOfYear := time.Date(date.Year(), 01, 01, 0, 0, 0, 0, time.UTC)
	yDay := date.Sub(startOfYear).Hours() / 24

	sunrise, sunset, err := p.GetSunriseSunset()

	if err != nil {
		fmt.Println(err)
	}

	expectedSunrise := sunrise.Hour()*60 + sunrise.Minute() - int(60*utcOffset)
	expectedSunset := sunset.Hour()*60 + sunset.Minute() - int(60*utcOffset)

	fmt.Printf(" { .in_latitude = %v, .in_longitude = %v, .in_yday = %v, .in_hour = %v, .expected_sunrise_mins = %v, .expected_sunset_mins = %v,},\n",
		latitude,
		longitude,
		yDay,
		0,
		expectedSunrise,
		expectedSunset)
}

func main() {
	fmt.Printf("// autogenerated file - do not modify\n")

	latitudeSaoPaulo := -23.545570
	longitudeSaoPaulo := -46.704082
	utcOffsetSaoPaulo := -3.0

	latitudeMalaga := 36.7201600
	longitudeMalaga := -4.4203400
	utcOffsetMalaga := 1.0

	latitudeDelhi := 28.613084
	longitudeDelhi := 77.209168
	utcOffsetDelhi := 5.5

	latitudeDallas := 32.755701
	longitudeDallas := -96.797296
	utcOffsetDallas := -5.0

	dateMar := time.Date(2017, 3, 23, 0, 0, 0, 0, time.UTC)
	dateJul := time.Date(2023, 7, 1, 0, 0, 0, 0, time.UTC)
	dateSep := time.Date(2040, 9, 6, 0, 0, 0, 0, time.UTC)
	dateDec := time.Date(2029, 12, 23, 0, 0, 0, 0, time.UTC)

	printOneLine(latitudeSaoPaulo, longitudeSaoPaulo, utcOffsetSaoPaulo, dateMar)
	printOneLine(latitudeSaoPaulo, longitudeSaoPaulo, utcOffsetSaoPaulo, dateJul)
	printOneLine(latitudeSaoPaulo, longitudeSaoPaulo, utcOffsetSaoPaulo, dateSep)
	printOneLine(latitudeSaoPaulo, longitudeSaoPaulo, utcOffsetSaoPaulo, dateDec)

	printOneLine(latitudeMalaga, longitudeMalaga, utcOffsetMalaga, dateMar)
	printOneLine(latitudeMalaga, longitudeMalaga, utcOffsetMalaga, dateJul)
	printOneLine(latitudeMalaga, longitudeMalaga, utcOffsetMalaga, dateSep)
	printOneLine(latitudeMalaga, longitudeMalaga, utcOffsetMalaga, dateDec)

	printOneLine(latitudeDelhi, longitudeDelhi, utcOffsetDelhi, dateMar)
	printOneLine(latitudeDelhi, longitudeDelhi, utcOffsetDelhi, dateJul)
	printOneLine(latitudeDelhi, longitudeDelhi, utcOffsetDelhi, dateSep)
	printOneLine(latitudeDelhi, longitudeDelhi, utcOffsetDelhi, dateDec)

	printOneLine(latitudeDallas, longitudeDallas, utcOffsetDallas, dateMar)
	printOneLine(latitudeDallas, longitudeDallas, utcOffsetDallas, dateJul)
	printOneLine(latitudeDallas, longitudeDallas, utcOffsetDallas, dateSep)
	printOneLine(latitudeDallas, longitudeDallas, utcOffsetDallas, dateDec)
}
