name: unit tests
on: [push, pull_request, workflow_dispatch]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with: { go-version: 1.x }
      - uses: actions/checkout@v2
      - name: run unit tests
        run: |
          cd tests
          make 
